### ISSUE TITLE
NoClassDefFoundError: javax.script.ScriptEngineManager under Java 11

### ISSUE THREAD

**Issue by kredel** [kredel/java-algebra-system#14]
Caused by: java.lang.NoClassDefFoundError: javax/script/ScriptEngineManager
	at org.apache.logging.log4j.core.script.ScriptManager.<init>(ScriptManager.java:49)
	at org.apache.logging.log4j.core.config.AbstractConfiguration.initialize(AbstractConfiguration.java:179)
	at org.apache.logging.log4j.core.config.builder.impl.DefaultConfigurationBuilder.build(DefaultConfigurationBuilder.java:174)
	at org.apache.logging.log4j.core.config.builder.impl.DefaultConfigurationBuilder.build(DefaultConfigurationBuilder.java:45)
	at org.apache.logging.log4j.core.config.properties.PropertiesConfigurationFactory.getConfiguration(PropertiesConfigurationFactory.java:170)
	at org.apache.logging.log4j.core.config.properties.PropertiesConfigurationFactory.getConfiguration(PropertiesConfigurationFactory.java:48)
	at org.apache.logging.log4j.core.config.ConfigurationFactory$Factory.getConfiguration(ConfigurationFactory.java:490)
	at org.apache.logging.log4j.core.config.ConfigurationFactory$Factory.getConfiguration(ConfigurationFactory.java:460)
	at org.apache.logging.log4j.core.config.ConfigurationFactory.getConfiguration(ConfigurationFactory.java:256)
	at org.apache.logging.log4j.core.LoggerContext.reconfigure(LoggerContext.java:561)
	at org.apache.logging.log4j.core.LoggerContext.reconfigure(LoggerContext.java:578)
	at org.apache.logging.log4j.core.LoggerContext.start(LoggerContext.java:214)
	at org.apache.logging.log4j.core.impl.Log4jContextFactory.getContext(Log4jContextFactory.java:145)
	at org.apache.logging.log4j.core.impl.Log4jContextFactory.getContext(Log4jContextFactory.java:41)
	at org.apache.logging.log4j.LogManager.getContext(LogManager.java:182)
	at org.apache.logging.log4j.LogManager.getLogger(LogManager.java:455)
	at edu.jas.poly.TermOrder.<clinit>(TermOrder.java:39)

**Comment by kredel** [comment]
found by Raphael

**Comment by kredel** [comment]
So far it seem to be fixed with Log4j2, version 2.13.2.
