### ISSUE TITLE
NullPointerException when parsing expression with denominator 1

### ISSUE THREAD

**Issue by kredel** [kredel/java-algebra-system#2]
Posted on Aug 7, 2014 by Swift Elephant

What steps will reproduce the problem? I don't know if the polynomial ring in 0 variable is supported. Anyway, execute the following test case: 

@Test public void testNullPointer() {
   GenPolynomialRing<BigRational> pfree = new GenPolynomialRing<BigRational>( new BigRational(), new String[] { }); 
 QuotientRing<BigRational> coeff = new QuotientRing<BigRational>(pfree); 
 coeff.parse("(0|1)");
 coeff.parse("(1|1)"); 
}

We will get the NPE: 
java.lang.NullPointerException 
at edu.jas.ufd.Quotient.<init>(Quotient.java:105) 
at edu.jas.ufd.Quotient.<init>(Quotient.java:77) 
at edu.jas.ufd.QuotientRing.parse(QuotientRing.java:380) 
at my.TestJas.testNullPointer(TestJas.java:300)

What is the expected output? What do you see instead? No NPE

What version of the product are you using? On what operating system? r4853. Windows 7

Please provide any additional information below.

**Comment by kredel** [comment]
Is fixed. Fix will be contained in next release.

**Comment by kredel** [comment]
Next release is published. Bug resolved.
