### ISSUE TITLE
JAS libs version 2.65851 commit broke compiling in Android Studio

### ISSUE THREAD

**Issue by axkr** [kredel/java-algebra-system#3]
See https://github.com/axkr/symja_android_library/issues/63

Do you have any idea what's the cause of the problem is?

**Comment by axkr** [comment]
We tracked down this problem to this exception:
```

07-14 03:02:29.799 17630-17630/br.eng.it.jsvcalc W/System.err: Caused by: java.lang.NullPointerException: Attempt to get length of null array
at org.apache.logging.log4j.util.ReflectionUtil$PrivateSecurityManager.getCallerClass(ReflectionUtil.java:308)
at org.apache.logging.log4j.util.ReflectionUtil.getCallerClass(ReflectionUtil.java:218)
07-14 03:02:29.800 17630-17630/br.eng.it.jsvcalc W/System.err: at org.apache.logging.log4j.util.ReflectionUtil.getCallerClass(ReflectionUtil.java:197)
at org.apache.logging.log4j.core.selector.ClassLoaderContextSelector.getContext(ClassLoaderContextSelector.java:72)
at org.apache.logging.log4j.core.selector.ClassLoaderContextSelector.getContext(ClassLoaderContextSelector.java:57)
at org.apache.logging.log4j.core.impl.Log4jContextFactory.getContext(Log4jContextFactory.java:140)
at org.apache.logging.log4j.core.impl.Log4jContextFactory.getContext(Log4jContextFactory.java:41)
07-14 03:02:29.801 17630-17630/br.eng.it.jsvcalc W/System.err: at org.apache.logging.log4j.LogManager.getContext(LogManager.java:267)
at org.apache.log4j.Logger$PrivateManager.getContext(Logger.java:59)
at org.apache.log4j.Logger.getLogger(Logger.java:41)
at edu.jas.kern.ComputerThreads.(ComputerThreads.java:30)

```

**Comment by kredel** [comment]
Since Apache log4j was not working on Android there is the adapter package [droidlog.jar](http://krum.rz.uni-mannheim.de/jas/droidlog.jar) which delegates the logging calls to native Android logging.
In case you can not use droidlog.jar and not Apache log4j for some reason, there is an adapter package [mylog.jar](http://krum.rz.uni-mannheim.de/jas/mylog.jar) which delegates the logging calls to native Java logging.
If these adapters do not work, please, reopen the issue.

**Comment by axkr** [comment]
This problem could be solved with slf4j-android and log4j-over-slf4j

See: https://github.com/axkr/symja_android_library/issues/63

**Comment by kredel** [comment]
the proposed solution with mylog.jar and/or nolog.jar doen't work at the moment. Class Logger is loaded from nolog.jar/mylog.jar, but then execution switches to java.util.logging.Logger (Java logging). Classes from log4j are not searched any more and none are used afterwords. We will investigate this issue.
